from typing import Any

class PyAsn1Error(Exception):
    # `Any` here as user can pass anything, these values are not processed, only stored and returned back
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def context(self) -> dict[str, Any]: ...

class ValueConstraintError(PyAsn1Error): ...
class SubstrateUnderrunError(PyAsn1Error): ...
class EndOfStreamError(SubstrateUnderrunError): ...
class UnsupportedSubstrateError(PyAsn1Error): ...

class PyAsn1UnicodeError(PyAsn1Error, UnicodeError):
    # `message` is passed to `PyAsn1Error` as positional argument
    def __init__(self, message: Any, unicode_error: UnicodeError | None = None) -> None: ...

class PyAsn1UnicodeDecodeError(PyAsn1UnicodeError, UnicodeDecodeError): ...
class PyAsn1UnicodeEncodeError(PyAsn1UnicodeError, UnicodeEncodeError): ...
