from collections.abc import Generator
from io import BytesIO, IOBase
from typing import Any, Literal, Protocol, type_check_only

from pyasn1 import error
from pyasn1.type import univ

@type_check_only
class _IsSeekable(Protocol):
    def seekable(self) -> bool: ...

@type_check_only
class _Peekable(Protocol):
    def peek(self, n: int) -> bytes: ...

@type_check_only
class _ReadSeekable(Protocol):
    def read(self, n: int) -> bytes: ...
    def seek(self, n: int, whence: int) -> int: ...

@type_check_only
class _SeekTellable(Protocol):
    def seek(self, n: int, whence: int) -> int: ...
    def tell(self) -> int: ...

@type_check_only
class _ReadSeekTellable(_SeekTellable):
    def read(self, n: int) -> bytes: ...

class CachingStreamWrapper(IOBase):
    def __init__(self, raw: IOBase) -> None: ...
    def peek(self, n: int) -> bytes: ...
    def seekable(self) -> Literal[True]: ...
    def seek(self, n: int = -1, whence: int = 0) -> int: ...
    def read(self, n: int = -1) -> bytes: ...

    @property
    def markedPosition(self) -> int: ...
    @markedPosition.setter
    def markedPosition(self, value: int) -> None: ...

    def tell(self) -> int: ...

def asSeekableStream(
    substrate: bytes | bytearray | memoryview | univ.OctetString | IOBase,  # `IOBase` per documentation
) -> BytesIO | CachingStreamWrapper | _IsSeekable: ...
def isEndOfStream(substrate: _ReadSeekTellable) -> Generator[bool | None]: ...
def peekIntoStream(
    substrate: _Peekable | _SeekTellable, size: int = -1
) -> Generator[bytes | error.SubstrateUnderrunError | None]: ...
def readFromStream(
    substrate: _ReadSeekable,
    size: int = -1,
    context: dict[str, Any] | None = None,  # `context` is passed to `error.PyAsn1Error` and not processed
) -> Generator[bytes | error.SubstrateUnderrunError]: ...
